# Generated by Django 4.1.5 on 2023-04-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=200, unique=True)),
                ("id_number", models.CharField(max_length=200, unique=True)),
                ("balance", models.IntegerField(default=0)),
                ("average_txn", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=250, unique=True)),
                ("transaction_type", models.CharField(max_length=200)),
                ("amount", models.CharField(max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.account",
                    ),
                ),
            ],
        ),
    ]
