# Generated by Django 4.1.7 on 2023-03-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_number',
            new_name='account',
        ),
    ]
