# Generated by Django 4.1.7 on 2023-03-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_balance', models.FloatField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
    ]
